name: Deploy Infrastructure
on:
  push:
    branches: ['**']

permissions:
  contents: read
  id-token: write

env:
  ENABLE_DOCKER_BUILD: false
  ENABLE_TERRAFORM_APPLY: false
  ENABLE_PRODUCTION_DEPLOY: false
  
  REGION: asia-northeast1
  TF_CLOUD_ORGANIZATION: "fact-checker"  # Organization名に変更

jobs:
  validate:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.env.outputs.environment }}
      branch_name: ${{ steps.env.outputs.branch_name }}
      app_name: ${{ steps.env.outputs.app_name }}
      workspace_name: ${{ steps.env.outputs.workspace_name }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set Environment Variables
        id: env
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            echo "environment=production" >> $GITHUB_OUTPUT
            echo "app_name=x-fact-checker-prod" >> $GITHUB_OUTPUT
            echo "workspace_name=fact-checker-fs" >> $GITHUB_OUTPUT
          else
            echo "environment=staging" >> $GITHUB_OUTPUT
            echo "app_name=x-fact-checker-staging" >> $GITHUB_OUTPUT
            echo "workspace_name=fact-checker-fs" >> $GITHUB_OUTPUT
          fi
          echo "branch_name=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          
          echo "=== Environment Detection ==="
          echo "Branch: ${{ github.ref_name }}"
          echo "Environment: $([ "${{ github.ref }}" = "refs/heads/main" ] && echo "production" || echo "staging")"
          echo "App Name: $([ "${{ github.ref }}" = "refs/heads/main" ] && echo "x-fact-checker-prod" || echo "x-fact-checker-staging")"
          echo "Workspace: fact-checker-fs"
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      
      - name: Terraform Init
        working-directory: ./infrastructure
        env:
          TF_WORKSPACE: ${{ steps.env.outputs.workspace_name }}
        run: terraform init
      
      - name: Terraform Validate
        working-directory: ./infrastructure
        env:
          TF_WORKSPACE: ${{ steps.env.outputs.workspace_name }}
        run: |
          echo "🔍 Terraform構文チェック実行"
          terraform validate
          echo "✅ Terraform構文チェック成功"
      
      - name: Terraform Plan (Dry Run)
        working-directory: ./infrastructure
        env:
          TF_WORKSPACE: ${{ steps.env.outputs.workspace_name }}
        run: |
          echo "🔍 Terraform Plan実行"
          terraform plan
          echo "✅ Terraform Plan成功"
          
          echo "=== 安全弁状況 ==="
          echo "ENABLE_DOCKER_BUILD: ${{ env.ENABLE_DOCKER_BUILD }}"
          echo "ENABLE_TERRAFORM_APPLY: ${{ env.ENABLE_TERRAFORM_APPLY }}"
          echo "ENABLE_PRODUCTION_DEPLOY: ${{ env.ENABLE_PRODUCTION_DEPLOY }}"

  docker-build:
    needs: validate
    runs-on: ubuntu-latest
    if: vars.ENABLE_DOCKER_BUILD == 'true'
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCLOUD_SERVICE_KEY }}
          project_id: ${{ secrets.PROJECT_ID }}
      
      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
      
      - name: Build and Push Docker Image
        env:
          APP_NAME: ${{ needs.validate.outputs.app_name }}
        run: |
          echo "🐳 Dockerイメージビルド開始"
          IMAGE_SHA="${{ env.REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/fact-checker-repo/${{ env.APP_NAME }}:${{ github.sha }}"
          IMAGE_LATEST="${{ env.REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/fact-checker-repo/${{ env.APP_NAME }}:latest"
          
          # Build and push with SHA tag
          gcloud builds submit --tag "$IMAGE_SHA" --quiet
          echo "✅ Dockerイメージビルド成功: $IMAGE_SHA"
          
          # Tag and push as latest
          gcloud container images add-tag "$IMAGE_SHA" "$IMAGE_LATEST" --quiet
          echo "✅ latest タグ作成完了: $IMAGE_LATEST"

  terraform-apply:
    needs: [validate, docker-build]
    runs-on: ubuntu-latest
    if: vars.ENABLE_TERRAFORM_APPLY == 'true' && (github.ref != 'refs/heads/main' || vars.ENABLE_PRODUCTION_DEPLOY == 'true')
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      
      - name: Terraform Init (Terraform Cloud)
        working-directory: ./infrastructure
        env:
          TF_WORKSPACE: ${{ needs.validate.outputs.workspace_name }}
        run: |
          echo "🚀 Initializing Terraform with Terraform Cloud..."
          terraform init
          echo "✅ Terraform initialization completed"
      
      - name: Create Secrets Only (First Step)
        working-directory: ./infrastructure
        env:
          TF_WORKSPACE: ${{ needs.validate.outputs.workspace_name }}
        run: |
          echo "🚀 Step 1: Creating Secret Manager secrets only..."
          terraform apply -auto-approve -target=module.secrets
          echo "✅ Secret Manager secrets created"
      
      - name: Set Secret Values
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
        run: |
          echo "📝 Setting placeholder values for secrets..."
          
          # Authenticate to Google Cloud
          echo '${{ secrets.GCLOUD_SERVICE_KEY }}' | base64 -d > /tmp/gcp-key.json
          gcloud auth activate-service-account --key-file=/tmp/gcp-key.json
          gcloud config set project ${{ secrets.PROJECT_ID }}
          
          # Set placeholder values for secrets
          SECRET_NAMES=("openai-api-key" "vector-store-id" "slack-bot-token" "slack-signing-secret" "slack-channel-id" "x-app-key" "x-app-secret" "x-access-token" "x-access-secret" "x-bearer-token" "cron-secret")
          for secret in "${SECRET_NAMES[@]}"; do
            echo "Setting placeholder value for ${{ needs.validate.outputs.environment }}-${secret}"
            echo "PLACEHOLDER_VALUE_${secret^^}" | gcloud secrets versions add ${{ needs.validate.outputs.environment }}-${secret} --data-file=- || true
          done
          
          echo "✅ プレースホルダー値設定完了"
          
      - name: Terraform Apply (Complete Infrastructure)
        working-directory: ./infrastructure
        env:
          TF_WORKSPACE: ${{ needs.validate.outputs.workspace_name }}
        run: |
          echo "🚀 Step 2: Deploying complete infrastructure..."
          echo "Environment: ${{ needs.validate.outputs.environment }}"
          echo "App Name: ${{ needs.validate.outputs.app_name }}"
          echo "Workspace: ${{ needs.validate.outputs.workspace_name }}"
          
          terraform apply -auto-approve
          echo "✅ Complete infrastructure deployment success"
          echo ""
          echo "⚠️  重要: 後で実際の値に更新してください"
          echo "https://console.cloud.google.com/security/secret-manager?project=${{ secrets.PROJECT_ID }}"
      
      - name: Get Service URL
        working-directory: ./infrastructure
        env:
          TF_WORKSPACE: ${{ needs.validate.outputs.workspace_name }}
        run: |
          SERVICE_URL=$(terraform output -raw service_url)
          echo "🌐 デプロイ完了: $SERVICE_URL"
          echo "SERVICE_URL=$SERVICE_URL" >> $GITHUB_ENV

  safety-report:
    needs: [validate]
    runs-on: ubuntu-latest
    if: always()
    
    steps:
      - name: Safety Status Report
        run: |
          echo "=== 🔒 安全弁状況レポート ==="
          echo "ENABLE_DOCKER_BUILD: ${{ vars.ENABLE_DOCKER_BUILD }}"
          echo "ENABLE_TERRAFORM_APPLY: ${{ vars.ENABLE_TERRAFORM_APPLY }}"
          echo "ENABLE_PRODUCTION_DEPLOY: ${{ vars.ENABLE_PRODUCTION_DEPLOY }}"
          echo ""
          echo "=== 📋 実行結果 ==="
          echo "✅ Phase 1 (Validate): 常に実行"
          echo "$([ '${{ vars.ENABLE_DOCKER_BUILD }}' = 'true' ] && echo '✅' || echo '❌') Phase 2 (Docker Build): ${{ vars.ENABLE_DOCKER_BUILD }}"
          echo "$([ '${{ vars.ENABLE_TERRAFORM_APPLY }}' = 'true' ] && echo '✅' || echo '❌') Phase 3 (Terraform Apply): ${{ vars.ENABLE_TERRAFORM_APPLY }}"
          echo ""
          echo "=== 📖 次のステップ ==="
          if [ "${{ vars.ENABLE_DOCKER_BUILD }}" != "true" ]; then
            echo "1. ENABLE_DOCKER_BUILD=trueに設定してDockerビルドをテスト"
          elif [ "${{ vars.ENABLE_TERRAFORM_APPLY }}" != "true" ]; then
            echo "2. ENABLE_TERRAFORM_APPLY=trueに設定してTerraformデプロイをテスト"
          elif [ "${{ vars.ENABLE_PRODUCTION_DEPLOY }}" != "true" ] && [ "${{ github.ref }}" = "refs/heads/main" ]; then
            echo "3. ENABLE_PRODUCTION_DEPLOY=trueに設定して本番デプロイを有効化"
          else
            echo "🎉 全ての安全弁が適切に設定されています"
          fi